// Quick Notes Types - Auto-generated by Cursor AI

export type NoteStatus = 'pending' | 'active' | 'completed';

export interface QuickNote {
  id: string;
  title: string;
  description: string | null;
  content: string | null;
  status: NoteStatus;
  user_id: string;
  tags: string[];
  is_pinned: boolean;
  created_at: string;
  updated_at: string;
}

export interface CreateNoteRequest {
  title: string;
  description?: string;
  content?: string;
  status?: NoteStatus;
  tags?: string[];
  is_pinned?: boolean;
}

export interface UpdateNoteRequest {
  title?: string;
  description?: string;
  content?: string;
  status?: NoteStatus;
  tags?: string[];
  is_pinned?: boolean;
}

export interface NotesResponse {
  data: QuickNote[] | null;
  error: string | null;
}

export interface NoteResponse {
  data: QuickNote | null;
  error: string | null;
}

