'use client';

// Quick Notes Page - Auto-generated by Cursor AI
// Tests: Frontend autonomy with real-time updates

import { useState, useEffect } from 'react';
import { supabase } from '@/lib/supabase';
import type { QuickNote, NoteStatus, CreateNoteRequest } from '@/types/quick-notes';

export default function QuickNotesPage() {
  const [notes, setNotes] = useState<QuickNote[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [filterStatus, setFilterStatus] = useState<NoteStatus | 'all'>('all');
  
  // Form state
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [content, setContent] = useState('');
  const [status, setStatus] = useState<NoteStatus>('pending');
  
  // Edit state
  const [editingId, setEditingId] = useState<string | null>(null);

  // Load notes
  useEffect(() => {
    loadNotes();
    
    // Subscribe to real-time changes
    const channel = supabase
      .channel('quick_notes_changes')
      .on(
        'postgres_changes',
        {
          event: '*',
          schema: 'public',
          table: 'quick_notes'
        },
        () => {
          loadNotes();
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, [filterStatus]);

  const loadNotes = async () => {
    try {
      setLoading(true);
      let query = supabase
        .from('quick_notes')
        .select('*')
        .order('created_at', { ascending: false });

      if (filterStatus !== 'all') {
        query = query.eq('status', filterStatus);
      }

      const { data, error } = await query;

      if (error) throw error;
      setNotes(data || []);
      setError(null);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const createNote = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!title.trim()) {
      setError('Title is required');
      return;
    }

    try {
      const newNote: CreateNoteRequest = {
        title,
        description,
        content,
        status
      };

      const response = await fetch('/api/quick-notes', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(newNote)
      });

      if (!response.ok) throw new Error('Failed to create note');

      // Clear form
      setTitle('');
      setDescription('');
      setContent('');
      setStatus('pending');
      
      loadNotes();
    } catch (err: any) {
      setError(err.message);
    }
  };

  const updateNote = async (id: string, updates: Partial<QuickNote>) => {
    try {
      const response = await fetch(`/api/quick-notes/${id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(updates)
      });

      if (!response.ok) throw new Error('Failed to update note');
      
      loadNotes();
      setEditingId(null);
    } catch (err: any) {
      setError(err.message);
    }
  };

  const deleteNote = async (id: string) => {
    if (!confirm('Delete this note?')) return;

    try {
      const response = await fetch(`/api/quick-notes/${id}`, {
        method: 'DELETE'
      });

      if (!response.ok) throw new Error('Failed to delete note');
      
      loadNotes();
    } catch (err: any) {
      setError(err.message);
    }
  };

  return (
    <div className="container mx-auto p-8 max-w-4xl">
      <h1 className="text-4xl font-bold mb-8">Quick Notes</h1>

      {/* Create Note Form */}
      <form onSubmit={createNote} className="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-8">
        <div className="mb-4">
          <input
            type="text"
            placeholder="Title"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700"
            required
          />
        </div>
        
        <div className="mb-4">
          <textarea
            placeholder="Description"
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700"
            rows={3}
          />
        </div>

        <div className="mb-4">
          <textarea
            placeholder="Content"
            value={content}
            onChange={(e) => setContent(e.target.value)}
            className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700"
            rows={5}
          />
        </div>

        <div className="mb-4">
          <select
            value={status}
            onChange={(e) => setStatus(e.target.value as NoteStatus)}
            className="shadow border rounded w-full py-2 px-3 text-gray-700"
          >
            <option value="pending">Pending</option>
            <option value="active">Active</option>
            <option value="completed">Completed</option>
          </select>
        </div>

        <button
          type="submit"
          className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
        >
          Create Note
        </button>
      </form>

      {/* Filter */}
      <div className="mb-4">
        <select
          value={filterStatus}
          onChange={(e) => setFilterStatus(e.target.value as NoteStatus | 'all')}
          className="shadow border rounded py-2 px-3"
        >
          <option value="all">All Notes</option>
          <option value="pending">Pending</option>
          <option value="active">Active</option>
          <option value="completed">Completed</option>
        </select>
      </div>

      {/* Error Message */}
      {error && (
        <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-4">
          {error}
        </div>
      )}

      {/* Loading State */}
      {loading && <div className="text-center py-8">Loading notes...</div>}

      {/* Notes List */}
      <div className="space-y-4">
        {notes.map((note) => (
          <div key={note.id} className="bg-white shadow-md rounded p-6">
            {editingId === note.id ? (
              <div>
                <input
                  type="text"
                  defaultValue={note.title}
                  className="border rounded px-2 py-1 w-full mb-2"
                  onBlur={(e) => updateNote(note.id, { title: e.target.value })}
                />
                <textarea
                  defaultValue={note.description || ''}
                  className="border rounded px-2 py-1 w-full mb-2"
                  rows={2}
                  onBlur={(e) => updateNote(note.id, { description: e.target.value })}
                />
                <button
                  onClick={() => setEditingId(null)}
                  className="text-sm text-blue-500"
                >
                  Done
                </button>
              </div>
            ) : (
              <div>
                <div className="flex justify-between items-start mb-2">
                  <h3 className="text-xl font-semibold">{note.title}</h3>
                  <span className={`px-3 py-1 rounded text-sm ${
                    note.status === 'completed' ? 'bg-green-100 text-green-800' :
                    note.status === 'active' ? 'bg-blue-100 text-blue-800' :
                    'bg-yellow-100 text-yellow-800'
                  }`}>
                    {note.status}
                  </span>
                </div>
                
                {note.description && (
                  <p className="text-gray-600 mb-2">{note.description}</p>
                )}
                
                {note.content && (
                  <p className="text-gray-700 mb-4">{note.content}</p>
                )}

                <div className="flex gap-2">
                  <button
                    onClick={() => setEditingId(note.id)}
                    className="text-sm text-blue-500 hover:text-blue-700"
                  >
                    Edit
                  </button>
                  <button
                    onClick={() => updateNote(note.id, { 
                      status: note.status === 'completed' ? 'pending' : 'completed' 
                    })}
                    className="text-sm text-green-500 hover:text-green-700"
                  >
                    {note.status === 'completed' ? 'Reopen' : 'Complete'}
                  </button>
                  <button
                    onClick={() => deleteNote(note.id)}
                    className="text-sm text-red-500 hover:text-red-700"
                  >
                    Delete
                  </button>
                </div>

                <div className="text-xs text-gray-400 mt-2">
                  Created: {new Date(note.created_at).toLocaleString()}
                </div>
              </div>
            )}
          </div>
        ))}

        {!loading && notes.length === 0 && (
          <div className="text-center py-8 text-gray-500">
            No notes yet. Create one above!
          </div>
        )}
      </div>
    </div>
  );
}

