// Quick Notes API - GET (list) and POST (create)
// Auto-generated by Cursor AI

import { createRouteHandlerClient } from '@supabase/auth-helpers-nextjs';
import { cookies} from 'next/headers';
import { NextResponse } from 'next/server';
import type { Database } from '@/types/supabase';
import type { CreateNoteRequest } from '@/types/quick-notes';

export async function GET(request: Request) {
  try {
    const supabase = createRouteHandlerClient<Database>({ cookies });
    
    // Verify authentication
    const { data: { session } } = await supabase.auth.getSession();
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Get query parameters
    const { searchParams } = new URL(request.url);
    const status = searchParams.get('status');

    let query = supabase
      .from('quick_notes')
      .select('*')
      .order('created_at', { ascending: false });

    // Filter by status if provided
    if (status && ['pending', 'active', 'completed'].includes(status)) {
      query = query.eq('status', status);
    }

    const { data, error } = await query;

    if (error) {
      console.error('Error fetching notes:', error);
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json({ data, error: null });
  } catch (error) {
    console.error('Unexpected error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export async function POST(request: Request) {
  try {
    const supabase = createRouteHandlerClient<Database>({ cookies });
    
    // Verify authentication
    const { data: { session } } = await supabase.auth.getSession();
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body: CreateNoteRequest = await request.json();

    // Validate required fields
    if (!body.title || body.title.trim() === '') {
      return NextResponse.json({ error: 'Title is required' }, { status: 400 });
    }

    // Insert note
    const { data, error } = await supabase
      .from('quick_notes')
      .insert({
        title: body.title,
        description: body.description || null,
        content: body.content || null,
        status: body.status || 'pending',
        tags: body.tags || [],
        is_pinned: body.is_pinned || false,
        user_id: session.user.id
      })
      .select()
      .single();

    if (error) {
      console.error('Error creating note:', error);
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json({ data, error: null }, { status: 201 });
  } catch (error) {
    console.error('Unexpected error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

